// 🐳 13F 발행사명 → 티커 매핑 — 13F엔 티커/CUSIP(유료)가 없어 발행사명만 옴. 거인 9인의 상위 보유 = 대부분 유명 대형주라
//   큐레이션 맵으로 커버(못 찾으면 null → 수익률 '—'). Yahoo 티커 형식(BRK-B 등). 정직: 매핑 확신되는 것만, 나머진 빈칸.
export const NAME_TO_TICKER: Record<string, string> = {
  // ── 메가캡 테크 ──
  'APPLE INC': 'AAPL', 'ALPHABET INC': 'GOOGL', 'MICROSOFT CORP': 'MSFT', 'AMAZON COM INC': 'AMZN',
  'META PLATFORMS INC': 'META', 'NVIDIA CORPORATION': 'NVDA', 'NVIDIA CORP': 'NVDA', 'MICRON TECHNOLOGY INC': 'MU',
  'TAIWAN SEMICONDUCTOR MANUFAC': 'TSM', 'ASML HLDG NV': 'ASML', 'BROADCOM INC': 'AVGO', 'SANDISK CORP': 'SNDK',
  'TERADYNE INC': 'TER', 'APPLOVIN CORP': 'APP', 'UBER TECHNOLOGIES INC': 'UBER', 'VERISIGN INC': 'VRSN',
  // ── 중국·해외 ADR ──
  'ALIBABA GROUP HLDG LTD': 'BABA', 'PDD HOLDINGS INC': 'PDD', 'TENCENT MUSIC ENTMT GROUP': 'TME',
  'NU HLDGS LTD': 'NU', 'COUPANG INC': 'CPNG', 'ANHEUSER BUSCH INBEV SA NV': 'BUD', 'COCA-COLA FEMSA SAB DE CV': 'KOF',
  // ── 버크셔 핵심 ──
  'AMERICAN EXPRESS CO': 'AXP', 'COCA COLA CO': 'KO', 'BANK AMERICA CORP': 'BAC', 'BK OF AMERICA CORP': 'BAC',
  'CHEVRON CORPORATION': 'CVX', 'CHEVRON CORP': 'CVX', 'OCCIDENTAL PETE CORP': 'OXY', 'CHUBB LTD SWITZ': 'CB',
  'CHUBB LTD': 'CB', 'MOODYS CORP': 'MCO', 'KRAFT HEINZ CO': 'KHC', 'DAVITA INC': 'DVA', 'KROGER CO': 'KR',
  'SIRIUSXM HOLDINGS INC': 'SIRI', 'DELTA AIR LINES INC': 'DAL', 'CAPITAL ONE FINL CORP': 'COF', 'ALLY FINL INC': 'ALLY',
  'NUCOR CORP': 'NUE', 'LENNAR CORP': 'LEN', 'NVR INC': 'NVR', 'LOUISIANA PAC CORP': 'LPX', 'CONSTELLATION BRANDS INC': 'STZ',
  'MACYS INC': 'M', 'JEFFERIES FINANCIAL GROUP IN': 'JEF', 'BERKSHIRE HATHAWAY INC DEL': 'BRK-B', 'HEICO CORP': 'HEI',
  // ── 산업·소비·금융 ──
  'CATERPILLAR INC': 'CAT', 'DEERE & CO': 'DE', 'FEDEX CORP': 'FDX', 'PACCAR INC': 'PCAR', 'CORNING INC': 'GLW',
  'ECOLAB INC': 'ECL', 'WALMART INC': 'WMT', 'WASTE MGMT INC DEL': 'WM', 'WASTE CONNECTIONS INC': 'WCN',
  'CLEAN HARBORS INC': 'CLH', 'CANADIAN NATL RY CO': 'CNI', 'BROOKFIELD CORP': 'BN', 'RESTAURANT BRANDS INTL INC': 'QSR',
  'WHIRLPOOL CORP': 'WHR', 'CARPENTER TECHNOLOGY CORP': 'CRS', 'MASTEC INC': 'MTZ', 'WEST PHARMACEUTICAL SVSC INC': 'WST',
  'HOWARD HUGHES HOLDINGS INC': 'HHH', 'CROCS INC': 'CROX', 'CARVANA CO': 'CVNA', 'HERTZ GLOBAL HLDGS INC': 'HTZ',
  'BLOCK H & R INC': 'HRB', 'EAST WEST BANCORP INC': 'EWBC', 'LPL FINL HLDGS INC': 'LPLA', 'VISA INC': 'V',
  'MASTERCARD INC': 'MA', 'NEW YORK TIMES CO': 'NYT',
  // ── 금융 데이터·전력 ──
  'S&P GLOBAL INC': 'SPGI', 'MSCI INC': 'MSCI', 'VISTRA CORP': 'VST', 'TALEN ENERGY CORP': 'TLN', 'NRG ENERGY INC': 'NRG',
  'MADISON SQUARE GRDN SPRT COR': 'MSGS', 'SEAPORT ENTMT GROUP INC': 'SEG',
}

// 발행사명 정규화 매칭 — 정확 일치 우선, 그 다음 접미사(NEW·CL A 등) 제거 후 재시도
export function issuerToTicker(name: string): string | null {
  const u = name.toUpperCase().trim()
  if (NAME_TO_TICKER[u]) return NAME_TO_TICKER[u]
  const stripped = u.replace(/\s+(NEW|CL [A-C]|CLASS [A-C]|COM|DEL|SWITZ)\b/g, '').replace(/\s+/g, ' ').trim()
  return NAME_TO_TICKER[stripped] ?? null
}
