// 오늘의 명언 167개 상수(투자 51 + 선생님 사진첩 116, 비율대로 섞음) — docs/student-mode/quotes.md 원문 확인 목록에서 scripts/generate-quotes.mjs 로 그대로 옮김(손으로 옮기지 않음)
export interface Quote {
  id: string
  person: string
  ko: string
  /** 원문(영문·한문·시). 사진첩의 한국어 글은 원문이 없어 빈 문자열 — 화면은 이때 '원문 보기'를 숨긴다 */
  original: string
  source: string
  /** 화면 표시용 — source 에서 마크다운 강조 기호와 "(화면에 ... 표기)" 같은 편집 지시 괄호를 뺀 문구 */
  sourceLabel: string
  /** B22 처럼 person 이 실제로 한 말을 다른 사람이 인용한 경우, 인용한 사람 */
  quotedBy?: string
  /** 표 각 행 출처엔 없고 소제목에만 있는 맥락(예: 템플턴 "16 Rules for Investment Success (1993)") */
  note?: string
}

export const QUOTES: Quote[] = [
  { id: "B01", person: "워런 버핏", ko: "다른 사람들이 탐욕스러울 때 두려워하고, 다른 사람들이 두려워할 때만 탐욕스러워지려 합니다.", original: "we simply attempt to be fearful when others are greedy and to be greedy only when others are fearful.", source: "1986 주주서한", sourceLabel: "1986 주주서한" },
  { id: "S001", person: "작자 미상", ko: "인생을 즐기세요. 시간이 얼마나 남았는지는 아무도 몰라요.", original: "Enjoy life! You never know how much time you have left.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "S002", person: "작자 미상", ko: "'어디를'보다는 '누구랑' 있느냐가 중요했다. '무엇을'보다는 '어떻게'가 중요했다. 하지만 제일 중요한 건 '왜?'였고, '언제?'에 대한 대답은 늘 지금이었다.", original: "", source: "선생님 사진첩 · 책 페이지(저자 미확인)", sourceLabel: "선생님 사진첩 · 책 페이지(저자 미확인)" },
  { id: "S003", person: "작자 미상", ko: "활동할 땐 바람처럼 빠르게, 고민할 땐 숲처럼 고요하게, 토의할 땐 불길처럼 맹렬하게, 주장할 땐 산처럼 묵직하게.", original: "其疾如風，其徐如林，侵掠如火，不動如山", source: "『손자병법』 「군쟁」 풍림화산(風林火山)을 풀어 쓴 글", sourceLabel: "『손자병법』 「군쟁」 풍림화산(風林火山)을 풀어 쓴 글" },
  { id: "B02", person: "워런 버핏", ko: "양말이든 주식이든, 저는 좋은 물건을 할인할 때 사는 걸 좋아합니다.", original: "Whether we're talking about socks or stocks, I like buying quality merchandise when it is marked down.", source: "2008 주주서한", sourceLabel: "2008 주주서한" },
  { id: "S005", person: "작자 미상", ko: "실수는 당신이 노력하고 있다는 증거예요.", original: "Mistakes are the proof that you are trying.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "S006", person: "람 이매뉴얼", ko: "위기를 낭비하지 마라. 이 말의 의미는 위기란 기존에는 할 수 없었던 방식으로 해볼 수 있는 기회라는 뜻이다.", original: "You never want a serious crisis to go to waste. And what I mean by that is an opportunity to do things that you think you could not do before.", source: "2008년 11월 월스트리트저널 CEO 회의 발언", sourceLabel: "2008년 11월 월스트리트저널 CEO 회의 발언" },
  { id: "B03", person: "워런 버핏", ko: "뛰어난 경영진이 이끄는 뛰어난 기업을 가졌다면, 우리가 가장 좋아하는 보유 기간은 '영원히'입니다.", original: "In fact, when we own portions of outstanding businesses with outstanding managements, our favorite holding period is forever.", source: "1988 주주서한", sourceLabel: "1988 주주서한" },
  { id: "S007", person: "김창옥", ko: "제 아무리 똑똑한 머리와 뛰어난 기술을 가지고 있어도 심장이 새의 심장이면 자기다운 삶을 살기가 어렵다. 그래서 우리는 사자가 뛰노는 곳으로 가야 한다. 야생사자를 만나서 내 안에 잠들어 있는 사자의 심장을 되찾아야 한다.", original: "", source: "선생님 사진첩 · 강연 카드", sourceLabel: "선생님 사진첩 · 강연 카드" },
  { id: "S008", person: "배철수", ko: "좋아하는 일이면 오래해. 오래하면 너 욕하던 놈들 다 사라지고 너만 남아.", original: "", source: "인스타그램 캘리 물빛(mulbitcalli) 게시글", sourceLabel: "인스타그램 캘리 물빛(mulbitcalli) 게시글" },
  { id: "B04", person: "워런 버핏", ko: "10년 동안 가질 생각이 없는 주식이라면 10분도 갖지 마세요.", original: "If you aren't willing to own a stock for ten years, don't even think about owning it for ten minutes.", source: "1996 주주서한", sourceLabel: "1996 주주서한" },
  { id: "S009", person: "Starra Neely Blade", ko: "지금 아무리 아파도, 언젠가 돌아보면 그 일이 삶을 더 좋은 쪽으로 바꿨다는 걸 알게 될 거예요.", original: "No matter how much it hurts now, one day you will look back and realize it changed your life for the better.", source: "선생님 사진첩 · 영문 카드(Positive Outlooks)", sourceLabel: "선생님 사진첩 · 영문 카드(Positive Outlooks)" },
  { id: "S010", person: "하혁진", ko: "타인을 공감하는 일보다 더 어려운 것은 자신을 공감하는 일이다.", original: "", source: "인스타그램 캘리 물빛(mulbitcalli) 게시글", sourceLabel: "인스타그램 캘리 물빛(mulbitcalli) 게시글" },
  { id: "S011", person: "작자 미상", ko: "자기를 지키는 가장 중요한 선택 가운데 하나는 언제 멈출지 선택하는 것이다.", original: "", source: "『사실은 많이 지쳐 있습니다』 · 인스타그램 캘리 물빛 게시글", sourceLabel: "『사실은 많이 지쳐 있습니다』 · 인스타그램 캘리 물빛 게시글" },
  { id: "B05", person: "워런 버핏", ko: "평범한 기업을 훌륭한 가격에 사는 것보다, 훌륭한 기업을 적당한 가격에 사는 편이 훨씬 낫습니다.", original: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", source: "1989 주주서한", sourceLabel: "1989 주주서한" },
  { id: "S012", person: "이소", ko: "우리에게 정말 중요한 건 '무얼 하면 좋을지' 주변을 살피는 일이 아닌 '무얼 하고 싶은지' 스스로 살피는 일이지 않을까요.", original: "", source: "『짧은 엽서를 부쳐요』 · 인스타그램 캘리 물빛 게시글", sourceLabel: "『짧은 엽서를 부쳐요』 · 인스타그램 캘리 물빛 게시글" },
  { id: "S013", person: "세하별", ko: "나의 힘듦은 영원하지 않다. 시간은 언제나 내 편이란 것을 잊지 말자.", original: "", source: "인스타그램 seha_byeol 게시글", sourceLabel: "인스타그램 seha_byeol 게시글" },
  { id: "B06", person: "워런 버핏", ko: "시간은 훌륭한 기업의 친구이고, 평범한 기업의 적입니다.", original: "Time is the friend of the wonderful business, the enemy of the mediocre.", source: "1989 주주서한", sourceLabel: "1989 주주서한" },
  { id: "S014", person: "작자 미상", ko: "당신의 삶을 산다고 남들이 미안하게 만들거나 죄책감을 갖게 두지 마세요. 당신 인생이에요. 원하는 대로 사세요.", original: "Don't let people make you feel bad or guilty for living your life. It is your life. Live it the way you want.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "S015", person: "작자 미상", ko: "무엇도 억지로 하지 말고 그냥 두세요. 될 일이면 될 거예요.", original: "Never force anything, just let it be. If it is meant to be, it will happen.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "B07", person: "워런 버핏", ko: "자기가 잘 아는 범위 안의 기업만 평가할 수 있으면 됩니다. 그 범위의 넓이는 중요하지 않지만, 경계를 아는 것은 꼭 필요합니다.", original: "You only have to be able to evaluate companies within your circle of competence. The size of that circle is not very important; knowing its boundaries, however, is vital.", source: "1996 주주서한", sourceLabel: "1996 주주서한" },
  { id: "S016", person: "작자 미상", ko: "아무리 좋은 사람이어도 누군가의 이야기 속에서는 늘 나쁜 사람이에요.", original: "No matter how good a person you are, you will always be bad in someone's story.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "S017", person: "작자 미상", ko: "겸손은 사람을 머물게 하고, 칭찬은 사람을 가깝게 하고, 넓음은 사람을 따르게 하고, 깊음은 사람을 감동케 한다.", original: "", source: "인스타그램 릴스 「리더들의 품격」", sourceLabel: "인스타그램 릴스 「리더들의 품격」" },
  { id: "B08", person: "워런 버핏", ko: "기관이든 개인이든 대부분의 투자자에게는 보수가 아주 낮은 인덱스펀드가 주식을 갖는 가장 좋은 방법입니다.", original: "Most investors, both institutional and individual, will find that the best way to own common stocks is through an index fund that charges minimal fees.", source: "1996 주주서한", sourceLabel: "1996 주주서한" },
  { id: "S018", person: "작자 미상", ko: "내가 가진 패를 다 보여주지 마세요. 사람을 잘 믿고 베풀어도 바닥에 떨어지게 되면 다 떠나버리더라구요. 두 개를 줄 수 있어도 하나만 주세요. 원래 인간 본연의 심리가 얻을 수 없다고 생각하는 순간 점점 멀어져가는 거예요.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "S019", person: "작자 미상", ko: "후회하기 싫으면 그렇게 살지 말고, 그렇게 살거면 후회하지 말아라.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "S020", person: "김도끼", ko: "사람이 사람에게 지치면 화를 내야 할 상황에도 화를 내지 않게 되고, 서운해야 할 상황에도 서운해하지 않게 된다.", original: "", source: "인스타그램 seha_byeol 게시글", sourceLabel: "인스타그램 seha_byeol 게시글" },
  { id: "B09", person: "워런 버핏", ko: "투자자는 흥분과 비용이 자신의 적이라는 걸 기억해야 합니다.", original: "Investors should remember that excitement and expenses are their enemies.", source: "2004 주주서한", sourceLabel: "2004 주주서한" },
  { id: "S021", person: "작자 미상", ko: "좋아하는데 이유가 있으면 존경이고, 좋아하는데 이유가 없으면 사랑이다.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "S022", person: "B.Oje", ko: "정해진 길이 어데 있노? 내가 가면 그저 거기가 길인갑다 하믄 되지.", original: "", source: "선생님 사진첩 · 그림 카드", sourceLabel: "선생님 사진첩 · 그림 카드" },
  { id: "B10", person: "워런 버핏", ko: "예측은 예측하는 사람에 대해서는 많은 걸 알려주지만, 미래에 대해서는 아무것도 알려주지 않습니다.", original: "The forecasts may tell you a great deal about the forecaster; they tell you nothing about the future.", source: "1980 주주서한", sourceLabel: "1980 주주서한" },
  { id: "S023", person: "여우별", ko: "다들 버티면서 살아. 안 버티고 사는 사람이 어딨어. 피곤해서 쉬고 싶은 날도 하고, 지쳐서 기운 하나 없는 날도 하고, 하기 싫고 못 하겠어도 버텨내고, 다 관두고 싶고 그만하고 싶어도 견뎌. 다들 그렇게 하루하루를 버텨내고 있어. 버티다 보면 결국 맞이할 그날을 위해서 오늘도 버텨보는 거야. 잘될 거니까.", original: "", source: "인스타그램 여우별_글", sourceLabel: "인스타그램 여우별_글" },
  { id: "S024", person: "작자 미상", ko: "이유 없이 만나는 사람은 친구, 이유 없으면 만나지 않는 사람은 지인, 이유를 만들어 만나고 싶은 사람은 좋아하는 사람.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "B11", person: "워런 버핏", ko: "누가 벌거벗고 수영하고 있었는지는 썰물이 되어야 알 수 있습니다.", original: "After all, you only find out who is swimming naked when the tide goes out.", source: "2001 주주서한", sourceLabel: "2001 주주서한" },
  { id: "S025", person: "작자 미상", ko: "너무 신경 쓰지 마세요. 너무 매달리지 마시고, 너무 불안해 하지도 마세요. 그게 무엇이든 다 지나가니까.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "S026", person: "작자 미상", ko: "성공하는 사람들은 믿기 때문에 보인다. 일반 사람들은 보이기 때문에 믿는다. 실패하는 사람들은 보고도 믿지 않는다.", original: "", source: "마윈(알리바바)의 말로 알려짐 · 원문 미확인", sourceLabel: "마윈(알리바바)의 말로 알려짐 · 원문 미확인" },
  { id: "S027", person: "작자 미상", ko: "완벽한 시기는 존재하지 않으며, 사람은 완벽이 아니라 완성도를 높이는 데 초점을 두고 사는 것이 중요하다. 완벽한 때를 기다리지 말자. 시작해 보고 실패하면 고쳐 나가면 된다. 빠르게 실패하는 것이 가장 빠르게 성공하는 길이다.", original: "", source: "『꽃은 누구에게나 핀다』 중에서(책속의 한줄)", sourceLabel: "『꽃은 누구에게나 핀다』 중에서(책속의 한줄)" },
  { id: "B12", person: "워런 버핏", ko: "계속 물이 새는 배에 타고 있다면, 구멍을 막는 데보다 배를 바꾸는 데 힘을 쓰는 편이 낫습니다.", original: "Should you find yourself in a chronically-leaking boat, energy devoted to changing vessels is likely to be more productive than energy devoted to patching leaks.", source: "1985 주주서한", sourceLabel: "1985 주주서한" },
  { id: "S028", person: "드라마 『그들이 사는 세상』", ko: "어머니가 말씀하셨다. 산다는 건 늘 뒤통수를 맞는 거라고. 나만이 아니라 누구나 뒤통수를 맞는 거라고. 그러니 억울해 말라고. 어머니는 또 말씀하셨다. 그러니 다 별일 아니라고.", original: "", source: "드라마 대사 · 캘리 happy_yuche", sourceLabel: "드라마 대사 · 캘리 happy_yuche" },
  { id: "S030", person: "작자 미상", ko: "타인의 삶과 비교하지 마라. 해와 달은 서로를 비교하는 법이 없다. 그들은 단지 그들의 시간대에서 빛나고 있을 뿐이다.", original: "", source: "붓다의 말로 알려짐 · 원문 미확인 · 캘리 sarangmi_calli", sourceLabel: "붓다의 말로 알려짐 · 원문 미확인 · 캘리 sarangmi_calli" },
  { id: "B13", person: "워런 버핏", ko: "정말 훌륭한 기업을 찾았다면 계속 함께하세요. 인내는 보답하고, 훌륭한 기업 하나가 피할 수 없는 수많은 평범한 결정을 메워 줍니다.", original: "When you find a truly wonderful business, stick with it. Patience pays, and one wonderful business can offset the many mediocre decisions that are inevitable.", source: "2023 주주서한", sourceLabel: "2023 주주서한" },
  { id: "S032", person: "작자 미상", ko: "긍정적으로 생각하기, 더 잘 먹기, 자주 운동하기, 기분 좋아지기. 그리고 다시 처음으로.", original: "Think positive → Eat better → Exercise often → Feel good", source: "선생님 사진첩 · 그림 카드(anxiety_wellbeing)", sourceLabel: "선생님 사진첩 · 그림 카드(anxiety_wellbeing)" },
  { id: "S034", person: "작자 미상", ko: "모든 게 좋아서 행복한 게 아니라, 모든 것의 좋은 면을 볼 수 있어서 행복한 거예요.", original: "Be happy not because everything is good, but because you can see the good side of everything.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "B14", person: "워런 버핏", ko: "오늘날 학생들은 케인스가 '새롭다'고 했던 것을 배웁니다. 저축에 복리를 더하면 놀라운 일이 일어난다는 것을요.", original: "Today, school children learn what Keynes termed \"novel\": combining savings with compound interest works wonders.", source: "2019 주주서한", sourceLabel: "2019 주주서한" },
  { id: "S035", person: "작자 미상", ko: "소통하고, 사과하고, 진실을 말하고, 남 탓 없이 책임을 받아들일 줄 알기 전까지는 어른이 아니에요.", original: "You're not grown up until you know how to communicate, apologize, be truthful and accept accountability without blaming someone else.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "S036", person: "신현봉", ko: "원하든 원하지 않든 가야 할 때가 있다. 다 버리고 떠나면 저 앞에는 또 만나야 할 인연이 있다.", original: "", source: "「인연」 · 글반장", sourceLabel: "「인연」 · 글반장" },
  { id: "B15", person: "워런 버핏", ko: "투자에서는 비관이 친구이고, 도취가 적입니다.", original: "When investing, pessimism is your friend, euphoria the enemy.", source: "2008 주주서한", sourceLabel: "2008 주주서한" },
  { id: "S038", person: "이평", ko: "너를 아껴줄 사람은 너 밖에 없다. 그러니까 사람 문제로 감정 낭비하지 말자. 갈 사람은 가고 올 사람은 다시 오니까.", original: "", source: "『꽃의 언어』 중에서", sourceLabel: "『꽃의 언어』 중에서" },
  { id: "S039", person: "작자 미상", ko: "좋아하는 일을 하는 것은 자유요, 하는 일을 좋아하는 것은 행복이다.", original: "", source: "메리 울스턴크래프트의 말로 알려짐 · 원문 미확인", sourceLabel: "메리 울스턴크래프트의 말로 알려짐 · 원문 미확인" },
  { id: "S040", person: "김수현", ko: "당신이 가장 존중해야 하는 사람은 언제나 당신 자신이다. 약간의 근자감과 어느 정도의 개썅마이웨이 정신이 필요하다!", original: "", source: "『나는 나로 살기로 했다』 · 글반장", sourceLabel: "『나는 나로 살기로 했다』 · 글반장" },
  { id: "B16", person: "워런 버핏", ko: "미스터 마켓은 여러분을 도우려고 있는 것이지, 이끌려고 있는 것이 아닙니다.", original: "Mr. Market is there to serve you, not to guide you.", source: "1987 주주서한", sourceLabel: "1987 주주서한" },
  { id: "S041", person: "작자 미상", ko: "바람이 부는 방향을 보고 서있으면 역풍이지만 바람을 등지면 순풍이 된다. 내 인생의 순풍과 역풍은 내가 행동하기에 따라 바뀐다.", original: "", source: "선생님 사진첩 · 한줄 명언 카드", sourceLabel: "선생님 사진첩 · 한줄 명언 카드" },
  { id: "S042", person: "가린", ko: "왜 모를까. 아무리 잘 맞는 사람이어도 관계를 오래 유지하기 위해선 서로를 지키기 위한 노력이 필요하다는 것을. 가만히 뒀는데도 잘 흘러가고 있는 건 상대가 그만큼 노력하고 있다는 것을.", original: "", source: "선생님 사진첩 · 책 페이지", sourceLabel: "선생님 사진첩 · 책 페이지" },
  { id: "B17", person: "워런 버핏", ko: "거시 경제를 전망하거나 남의 시장 예측을 듣는 것은 시간 낭비입니다.", original: "Forming macro opinions or listening to the macro or market predictions of others is a waste of time.", source: "2013 주주서한", sourceLabel: "2013 주주서한" },
  { id: "S043", person: "작자 미상", ko: "그러니 누구의 '탓'이 아니라 당신의 '몫'을 해나가라. 노력이 항상 좋은 결실을 맺지는 못하더라도, 그 결과가 당신의 마음에 차지 않을지라도, 삶의 용기란 그럼에도 불구하고 스스로의 몫에서 도망치지 않는 것이다.", original: "", source: "선생님 사진첩 · 책 페이지(저자 미확인)", sourceLabel: "선생님 사진첩 · 책 페이지(저자 미확인)" },
  { id: "S044", person: "최동훈", ko: "이제 다 내려놓을 거야. 싫어하면 할수록 힘든 것도 나고, 미워할수록 괴로운 것도 나야.", original: "", source: "선생님 사진첩 · 명언 카드", sourceLabel: "선생님 사진첩 · 명언 카드" },
  { id: "B18", person: "워런 버핏", ko: "시장 예측가는 여러분의 귀는 채워 주겠지만 지갑은 절대 채워 주지 않습니다.", original: "Market forecasters will fill your ear but will never fill your wallet.", source: "2014 주주서한", sourceLabel: "2014 주주서한" },
  { id: "S045", person: "영화 『우리들의 행복한 시간』", ko: "남들이 보기에는 먼지만한 가시 같아도 그게 내 상처일 때에는 우주보다도 더 아픈 거예요.", original: "", source: "영화 대사 · 명언 카드", sourceLabel: "영화 대사 · 명언 카드" },
  { id: "S046", person: "작자 미상", ko: "\"그건 불가능해,\" 자존심이 말했다. \"그건 위험하지,\" 경험이 말했다. \"그건 무의미해,\" 이성이 말했다. \"한번 해봐,\" 가슴이 속삭였다.", original: "", source: "선생님 사진첩 · 캘리 카드", sourceLabel: "선생님 사진첩 · 캘리 카드" },
  { id: "B19", person: "워런 버핏", ko: "큰 투자자든 작은 투자자든 비용이 낮은 인덱스펀드를 꾸준히 가져가야 합니다.", original: "Both large and small investors should stick with low-cost index funds.", source: "2016 주주서한", sourceLabel: "2016 주주서한" },
  { id: "S047", person: "작자 미상", ko: "인생이 마음 같지 않아도, 오늘을 잘 견뎌낸 나 자신에게 고마워하자.", original: "", source: "선생님 사진첩 · 그림 카드(궁금해 뭘까)", sourceLabel: "선생님 사진첩 · 그림 카드(궁금해 뭘까)" },
  { id: "S048", person: "작자 미상", ko: "생각이 많아지면 용기는 줄어든다. 적당한 생각은 지혜를 주지만 과도한 생각은 결국 나를 겁쟁이로 만드는 잡념에 불과하다.", original: "", source: "에르빈 롬멜의 말로 알려짐 · 원문 미확인", sourceLabel: "에르빈 롬멜의 말로 알려짐 · 원문 미확인" },
  { id: "S049", person: "신준모", ko: "누구나 외롭다. 누구나 힘들다. 다들 아닌 척 살아갈 뿐이다.", original: "", source: "『어떤 하루』 중에서", sourceLabel: "『어떤 하루』 중에서" },
  { id: "B20", person: "워런 버핏", ko: "크고 '쉬운' 결정을 붙잡고, 잦은 매매는 피하세요.", original: "A final lesson from our bet: Stick with big, \"easy\" decisions and eschew activity.", source: "2017 주주서한", sourceLabel: "2017 주주서한" },
  { id: "S050", person: "아나이스 닌", ko: "삶은 사람의 용기에 비례하여 넓어지거나 줄어든다.", original: "Life shrinks or expands in proportion to one's courage.", source: "『아나이스 닌의 일기』 3권 1941년 6월", sourceLabel: "『아나이스 닌의 일기』 3권 1941년 6월" },
  { id: "S051", person: "박대선", ko: "세상의 평가 따위는 집어 치고 타인의 시선 따위는 접어 두고, 내 마음에 드는지 확인하고 내가 행복한지 확인할 것.", original: "", source: "『서툰어른처방전』 「나에게 미안하지 않는 법」", sourceLabel: "『서툰어른처방전』 「나에게 미안하지 않는 법」" },
  { id: "B21", person: "워런 버핏", ko: "영구적인 원금 손실의 위험은 절대 지지 마세요.", original: "Never risk permanent loss of capital.", source: "2023 주주서한", sourceLabel: "2023 주주서한" },
  { id: "S052", person: "작자 미상", ko: "젊음은 사그라들고 여름은 흘러가고 생은 소멸한다. 시간은 유한하며 되돌릴 수 없다. 두 번의 기회는 없다는 것, 그게 철학이 필요한 이유다.", original: "", source: "선생님 사진첩 · 책 카드(저자 미확인)", sourceLabel: "선생님 사진첩 · 책 카드(저자 미확인)" },
  { id: "S053", person: "작자 미상", ko: "힘들다는 건 좋은 일이 다가올려고 하는 거니까 우리 조금만 참아요.", original: "", source: "선생님 사진첩 · 캘리 카드", sourceLabel: "선생님 사진첩 · 캘리 카드" },
  { id: "B22", person: "벤저민 그레이엄", ko: "오래전 벤 그레이엄이 가르쳐 주었습니다. \"가격은 여러분이 내는 것이고, 가치는 여러분이 얻는 것입니다.\"", original: "Long ago, Ben Graham taught me that \"Price is what you pay; value is what you get.\"", source: "2008 주주서한 — **그레이엄의 말을 버핏이 인용** (화면에 그렇게 표기)", sourceLabel: "2008 주주서한 — 그레이엄의 말을 버핏이 인용", quotedBy: "워런 버핏" },
  { id: "S054", person: "손정은", ko: "지켜야 할 선이 있고 넘어야 할 선이 있습니다. 지켜야 하는 선은 양심이고 넘어야 할 선은 한계입니다. 지금 내 앞에 두 개의 선이 있습니다. 어느 선을 지키고 어느 선을 넘겠습니까?", original: "", source: "『건강한 영혼을 위한 70가지 이야기』 중에서", sourceLabel: "『건강한 영혼을 위한 70가지 이야기』 중에서" },
  { id: "S055", person: "작자 미상", ko: "그래 그냥 그렇게 흘러가듯이 사는 게야.", original: "", source: "선생님 사진첩 · 캘리 카드", sourceLabel: "선생님 사진첩 · 캘리 카드" },
  { id: "S056", person: "박노해", ko: "제대로 심판하지 않으면 '악의 용기'는 대물림된다. 잘못하면 벌 받는다는 '두려움의 전율'이 흐르게 해야 한다.", original: "If not judged properly, the 'courage of evil' will be transmitted. The 'thrill of fear' of being punished for doing wrong must be made to flow.", source: "「박노해의 걷는 독서」", sourceLabel: "「박노해의 걷는 독서」" },
  { id: "L01", person: "피터 린치", ko: "공부 없이 투자하는 것은 카드를 보지 않고 포커를 치는 것과 같습니다.", original: "Investing without research is like playing stud poker and never looking at the cards.", source: "『전설로 떠나는 월가의 영웅(One Up on Wall Street)』 1989", sourceLabel: "『전설로 떠나는 월가의 영웅(One Up on Wall Street)』 1989" },
  { id: "S057", person: "드라마 대사", ko: "악은 이토록 거침없이 자신의 길을 가는데 어째서 선은 끊임없이 자신을 증명해야 하는가?", original: "", source: "선생님 사진첩 · 드라마 장면(작품 미확인)", sourceLabel: "선생님 사진첩 · 드라마 장면(작품 미확인)" },
  { id: "S058", person: "작자 미상", ko: "좋은 생각을 가지면 어긋날 일이 없고, 부드러운 혀를 가지면 다툴 일이 없고, 온유한 귀를 가지면 화날 일이 없고, 겸손한 마음을 가지면 불편할 일이 없습니다. 인생을 유연하게 물처럼 부드럽게 삽시다.", original: "", source: "선생님 사진첩 · 「…가지면」 카드", sourceLabel: "선생님 사진첩 · 「…가지면」 카드" },
  { id: "L02", person: "피터 린치", ko: "기본 사업을 이해하면 회사 이야기를 알기가 훨씬 쉽습니다. 그래서 저는 통신위성보다 스타킹에, 광섬유보다 모텔 체인에 투자하겠습니다.", original: "Getting the story on a company is a lot easier if you understand the basic business. That's why I'd rather invest in panty hose than in communications satellites, or in motel chains than in fiber optics.", source: "『One Up on Wall Street』 1989", sourceLabel: "『One Up on Wall Street』 1989" },
  { id: "S059", person: "작자 미상", ko: "고맙습니다. 미안합니다. 응원합니다.", original: "", source: "선생님 사진첩 · 그림 카드", sourceLabel: "선생님 사진첩 · 그림 카드" },
  { id: "S061", person: "원태연", ko: "소심하다는 것은 상처가 많다는 것이다. 그래서 상처가 있는 사람들은 미연에 그것을 방지한다. 상처받기 싫어서. 그리고 그 상처는 마음속에 깊이 남아 마음이 아닌 뇌에 각인된다. 그리고는 그 상처는 곧 그 사람 자신이 된다.", original: "", source: "『슬픔보다 더 슬픈 이야기』 중에서", sourceLabel: "『슬픔보다 더 슬픈 이야기』 중에서" },
  { id: "L03", person: "피터 린치", ko: "크레용으로 그려서 설명할 수 없는 아이디어에는 절대 투자하지 마세요.", original: "Never invest in any idea you can't illustrate with a crayon.", source: "『피터 린치의 이기는 투자(Beating the Street)』 1993", sourceLabel: "『피터 린치의 이기는 투자(Beating the Street)』 1993" },
  { id: "S062", person: "미소", ko: "나이드니 다 귀찮다. 안 맞는 사람 맞춰주는 것도, 싫다고 떠나는 사람 잡는 것도, 오해한 사람에게 해명하는 것도. 니들 알아서 하세요.", original: "", source: "인스타그램 mi_so_s2 그림 게시글", sourceLabel: "인스타그램 mi_so_s2 그림 게시글" },
  { id: "S063", person: "감성열차", ko: "사는 게 나만 울퉁불퉁 모난 모양처럼 느껴져도 들여다보면 각기 아픈 모양 하나쯤은 마음속에 갖고 있더라.", original: "", source: "캘리 happy_yuche 게시글", sourceLabel: "캘리 happy_yuche 게시글" },
  { id: "L04", person: "피터 린치", ko: "모든 주식 뒤에는 회사가 있습니다. 그 회사가 무엇을 하는지 알아내세요.", original: "Behind every stock is a company. Find out what it's doing.", source: "『Beating the Street』 — 20가지 황금 원칙", sourceLabel: "『Beating the Street』 — 20가지 황금 원칙" },
  { id: "S064", person: "글수지곰", ko: "잘해야 된다고 마음먹는 순간 인생은 피곤해진다. 그냥 하면 돼.", original: "", source: "인스타그램 geul_sujigom · 캘리 yuche", sourceLabel: "인스타그램 geul_sujigom · 캘리 yuche" },
  { id: "S065", person: "작자 미상", ko: "아오시발. 맑을 아(雅), 미워할 오(惡), 때 시(時), 다스릴 발(撥). 미워하는 마음도 맑게 다스릴 때이다.", original: "雅惡時撥", source: "선생님 사진첩 · 한자 말장난 카드", sourceLabel: "선생님 사진첩 · 한자 말장난 카드" },
  { id: "S066", person: "이근후", ko: "살아보니 인생은 필연보다 우연에 좌우되었고 세상은 생각보다 불합리하고 우스꽝스러운 곳이었다. 산다는 것은 슬픈 일이지만, 사소한 즐거움을 잃지 않는 한 인생은 무너지지 않는다.", original: "", source: "정신과 전문의 이근후 교수 · 인터뷰 카드", sourceLabel: "정신과 전문의 이근후 교수 · 인터뷰 카드" },
  { id: "L05", person: "피터 린치", ko: "무엇을 가졌는지, 그리고 왜 가졌는지 알아야 합니다.", original: "You have to know what you own, and why you own it.", source: "『Beating the Street』 — 20가지 황금 원칙", sourceLabel: "『Beating the Street』 — 20가지 황금 원칙" },
  { id: "S067", person: "작자 미상", ko: "첫째, 생각하라. 둘째, 믿어라. 셋째, 꿈꿔라. 그리고 마지막으로 덤벼들어라. 꿈꿀 수 있다면 이룰 수 있다. 내 모든 것이 꿈과 생쥐 한 마리로 시작했다는 것을 늘 기억하라. 왜 걱정하는가? 최선을 다했다면, 걱정한다고 더 나아지지 않는다.", original: "", source: "월트 디즈니의 말로 알려짐 · 원문 미확인 · 인스타그램 jason_j_cho", sourceLabel: "월트 디즈니의 말로 알려짐 · 원문 미확인 · 인스타그램 jason_j_cho" },
  { id: "S068", person: "작자 미상", ko: "오랜 관계를 위해서는 모든 관계에 적당한 거리가 필요하다. 자신에게 집중할수록 관계는 더 좋아진다. 미움도 서운함도 줄어들고 이해가 생긴다.", original: "", source: "펌글 · 캘리 happy_yuche", sourceLabel: "펌글 · 캘리 happy_yuche" },
  { id: "L06", person: "피터 린치", ko: "주식을 갖는 것은 아이를 키우는 것과 같습니다. 감당할 수 있는 것보다 많이 떠맡지 마세요.", original: "Owning stocks is like having children—don't get involved with more than you can handle.", source: "『Beating the Street』 — 20가지 황금 원칙", sourceLabel: "『Beating the Street』 — 20가지 황금 원칙" },
  { id: "S069", person: "작자 미상", ko: "너무 바쁜 일상을 살다 보면 가끔씩 잊고 살게 되는 것 같다. 나는 그저 날씨가 좋다는 이유 하나만으로도 얼마든지 행복할 수 있는 사람이라는 사실을.", original: "", source: "『스무살의 시선』 · 캘리 happy_yuche", sourceLabel: "『스무살의 시선』 · 캘리 happy_yuche" },
  { id: "S070", person: "작자 미상", ko: "집, 사무실, 책, 침대, 자주 쓰는 건 항상 최고로 근사해야 해요. 내가 그 안에서 살아야 하니까요. 사람도 똑같아요. 자주 만나는 사람, 매일 보는 사람은 근사한 사람들이어야 하죠. 내가 그 안에서 사니까요. 멀리할 사람은 멀리합시다. 좋은 사람들과 행복하기에도 인생은 너무 짧답니다.", original: "", source: "펌글 · 캘리 happy_yuche", sourceLabel: "펌글 · 캘리 happy_yuche" },
  { id: "L07", person: "피터 린치", ko: "주식으로 돈을 버는 열쇠는 겁에 질려 주식에서 도망치지 않는 것입니다.", original: "The key to making money in stocks is not to get scared out of them.", source: "『Beating the Street』 1993", sourceLabel: "『Beating the Street』 1993" },
  { id: "S071", person: "산배", ko: "안 될 생각하지 마라. 잘 될 생각만 해도 인생은 벅차다.", original: "", source: "인스타그램 sanbae_writer · 캘리 happy_yuche", sourceLabel: "인스타그램 sanbae_writer · 캘리 happy_yuche" },
  { id: "S072", person: "작자 미상", ko: "인생 뭐 있어. 살다 보면 보석 같은 순간들을 만나고 그 기억들을 목걸이처럼 꿰어 가지고 있다가 가끔 들여다보고 그 순간들의 힘으로 사는 거야. 그리고 그런 순간들이 많은 사람이 행복한 거야.", original: "", source: "『인생의 해상도』 · 캘리 happy_yuche", sourceLabel: "『인생의 해상도』 · 캘리 happy_yuche" },
  { id: "L08", person: "피터 린치", ko: "오래도록 잘되는 주식은 오래도록 잘되는 회사의 주식입니다. 성공 투자의 열쇠는 성공하는 회사를 찾는 것입니다.", original: "Stocks that do well in the long run belong to companies that do well in the long run. The key to successful investing is finding successful companies.", source: "『Learn to Earn』 1995", sourceLabel: "『Learn to Earn』 1995" },
  { id: "S073", person: "작자 미상", ko: "틀린 길은 없으니까 불안해하지 말자. 가장 짧은 길도 먼 길도 모두 맞는 길이야. 조급해하지 마.", original: "", source: "달콤 × 가온글씨 캘리 카드", sourceLabel: "달콤 × 가온글씨 캘리 카드" },
  { id: "S074", person: "공지영", ko: "나이를 먹어 좋은 일이 많습니다. 조금 무뎌졌고 조금 더 너그러워질 수 있으며 조금 더 기다릴 수 있습니다. 무엇보다 저 자신에게 그렇습니다.", original: "", source: "『빗방울처럼 나는 혼자였다』 · 글반장", sourceLabel: "『빗방울처럼 나는 혼자였다』 · 글반장" },
  { id: "S075", person: "작자 미상", ko: "현명한 사람이 되려거든 사리에 맞게 묻고 조심스럽게 듣고 침착하게 대답하라. 그리고 더 할 말이 없으면 침묵하라.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "G01", person: "벤저민 그레이엄", ko: "건전한 투자의 비밀을 세 단어로 줄이라면, 우리는 이 말을 내놓겠습니다. 안전마진.", original: "Confronted with a like challenge to distill the secret of sound investment into three words, we venture the motto, MARGIN OF SAFETY.", source: "『현명한 투자자』 1959년판", sourceLabel: "『현명한 투자자』 1959년판" },
  { id: "S076", person: "운산 최미숙", ko: "너는 이미 빛나고 있단다. 내일은 더 빛날 것이야.", original: "", source: "캘리그래피 작품", sourceLabel: "캘리그래피 작품" },
  { id: "S077", person: "작자 미상", ko: "잘 되는 거 별거 없어. 지금 나의 레벨에서 무리하지 않고 무너지지 않고 할 수 있는 걸 하고 있다면 그게 바로 잘 하는 거야.", original: "", source: "『오늘도 잘 살았네』 · 캘리 happy_yuche", sourceLabel: "『오늘도 잘 살았네』 · 캘리 happy_yuche" },
  { id: "G02", person: "벤저민 그레이엄", ko: "투자는 가장 사업처럼 할 때 가장 현명합니다.", original: "Investment is most intelligent when it is most businesslike.", source: "『현명한 투자자』 1959년판", sourceLabel: "『현명한 투자자』 1959년판" },
  { id: "S078", person: "신우", ko: "그동안 아무렇지 않은 척 하느라 애썼어.", original: "", source: "인스타그램 damso_calli 캘리 게시글", sourceLabel: "인스타그램 damso_calli 캘리 게시글" },
  { id: "S079", person: "작자 미상", ko: "좋은 사람들과 좋은 곳에서 좋은 시간을 가지는 것, 이걸 두 글자로 줄이면 '행복'이야.", original: "", source: "인스타그램 jyeonnvely(decoi_) 그림 게시글", sourceLabel: "인스타그램 jyeonnvely(decoi_) 그림 게시글" },
  { id: "G03", person: "벤저민 그레이엄", ko: "진정한 투자자에게 가격 변동의 의미는 하나뿐입니다. 크게 떨어지면 현명하게 살 기회, 크게 오르면 현명하게 팔 기회입니다.", original: "Basically, price fluctuations have only one significant meaning for the true investor. They provide him with an opportunity to buy wisely when prices fall sharply and to sell wisely when they advance a great deal.", source: "『현명한 투자자』 1959년판", sourceLabel: "『현명한 투자자』 1959년판" },
  { id: "S080", person: "정호승", ko: "새들은 바람이 가장 강하게 부는 날 집을 짓는다.", original: "", source: "캘리 인정 작품(정호승 시 구절)", sourceLabel: "캘리 인정 작품(정호승 시 구절)" },
  { id: "S081", person: "작자 미상", ko: "게으른 사람에게는 돈이 따르지 않고 변명하는 사람에게는 발전이 따르지 않는다. 거짓말 하는 사람에게는 희망이 따르지 않고 간사한 사람에게는 친구가 따르지 않는다. 자기만 생각하는 사람에게는 사랑이 따르지 않고 비교하는 사람에게는 만족이 따르지 않는다.", original: "", source: "『늦었지만 서울대 다녀오겠습니다』 저자 게시글(작자 미상 표기)", sourceLabel: "『늦었지만 서울대 다녀오겠습니다』 저자 게시글(작자 미상 표기)" },
  { id: "S082", person: "심윤경", ko: "살면서 중요하다고 생각해 왔던 것들이 실제로는 대단치도 않았다. 그것들을 내려놓고서도 나는 끄떡없이 달렸다. 반면 내가 대단치 않게 여겼던 것들이 실제로는 중요했다. 예를 들면 나 자신.", original: "", source: "『사랑이 달리다』 · 캘리 happy_yuche", sourceLabel: "『사랑이 달리다』 · 캘리 happy_yuche" },
  { id: "G04", person: "벤저민 그레이엄", ko: "주식시장은 저울이 아니라 투표 기계입니다.", original: "The stock market is a voting machine rather than a weighing machine.", source: "『증권분석』 1934년판", sourceLabel: "『증권분석』 1934년판" },
  { id: "S083", person: "셰익스피어", ko: "있다고 다 보여주지 말고, 안다고 다 말하지 말고, 가졌다고 다 빌려주지 말고, 들었다고 다 믿지 말고.", original: "Have more than thou showest, Speak less than thou knowest, Lend less than thou owest… Learn more than thou trowest.", source: "『리어왕』 1막 4장 광대의 노래 · 고운캘리 2025.02", sourceLabel: "『리어왕』 1막 4장 광대의 노래 · 고운캘리 2025.02" },
  { id: "S084", person: "이공이오", ko: "처음 마음을 먹는 것보다 돌아선 마음을 바꾸는 건 훨씬 어려운 일이다.", original: "", source: "「감정수학자」 · 시샘달 · 고운은주캘리", sourceLabel: "「감정수학자」 · 시샘달 · 고운은주캘리" },
  { id: "F01", person: "필립 피셔", ko: "주식을 살 때 공부를 제대로 했다면, 팔아야 할 때는 거의 없습니다.", original: "If the job has been correctly done when a common stock is purchased, the time to sell it is—almost never.", source: "『위대한 기업에 투자하라』 1958", sourceLabel: "『위대한 기업에 투자하라』 1958" },
  { id: "S085", person: "작자 미상", ko: "만날 사람은 만나게 되어 있고 떠날 사람은 떠나게 되어 있다. 그러니 뜻대로 이루어지지 않는 관계에 자주 초라해지지 않았으면 한다.", original: "", source: "선생님 사진첩 · 글 카드", sourceLabel: "선생님 사진첩 · 글 카드" },
  { id: "S086", person: "꼬마숙녀", ko: "조언, 충고, 평가는 함부로 하지 마라. 상대방이 물어봤을 때 그때 하는 거란다.", original: "", source: "마음송이 캘리 작품", sourceLabel: "마음송이 캘리 작품" },
  { id: "F02", person: "필립 피셔", ko: "지금 모두가 하는 일, 그래서 나도 참기 힘들 만큼 하고 싶은 일이 사실은 완전히 틀린 일인 경우가 많습니다.", original: "Doing what everybody else is doing at the moment, and therefore what you have an almost irresistible urge to do, is often the wrong thing to do at all.", source: "『위대한 기업에 투자하라』 1958", sourceLabel: "『위대한 기업에 투자하라』 1958" },
  { id: "S087", person: "이공이오", ko: "더 좋은 일들이 있으려고 그런 거겠지. 다 잘 지나갈 거야.", original: "", source: "「감정수학자」 · 시샘달 · 고운은주캘리", sourceLabel: "「감정수학자」 · 시샘달 · 고운은주캘리" },
  { id: "S088", person: "도기", ko: "살다 보면 어른이 되어야지만 알 수 있는 것들이 있다. 남을 미워하는 것보다 남을 용서하는 것이 편하다는 것, 나쁜 사람도 많지만 그만큼 좋은 사람도 많다는 것, 인생은 날씨와 같아서 슬프고 괴로운 날도 있고 행복하고 좋은 날도 있다는 것, 결국 모든 게 지나가고 나를 사랑해 줄 사람은 바로 나 자신뿐이라는 것.", original: "", source: "캘리 happy_yuche 게시글", sourceLabel: "캘리 happy_yuche 게시글" },
  { id: "T01", person: "존 템플턴", ko: "실수를 피하는 유일한 방법은 투자하지 않는 것입니다. 그런데 그게 가장 큰 실수입니다.", original: "The only way to avoid mistakes is not to invest—which is the biggest mistake of all.", source: "16가지 원칙 중 11번", sourceLabel: "16가지 원칙 중 11번", note: "16 Rules for Investment Success (1993)" },
  { id: "S089", person: "공병각", ko: "앞에서 못하는 말은 뒤에서도 하지 마요. 세상에 비밀은 없어요. 착한 말로 할 때 알아들어 먹어요. 또 그러면 머리 쪼갤 거야.", original: "", source: "공병각 캘리 작품", sourceLabel: "공병각 캘리 작품" },
  { id: "S090", person: "드라마 『연애의 발견』", ko: "네가 하고 싶은 대로 하고 살아. 울면서 견디든 도망치든 네 인생이니까.", original: "", source: "드라마 대사 · 캘리 yuche", sourceLabel: "드라마 대사 · 캘리 yuche" },
  { id: "S091", person: "아이열원", ko: "사랑이든 우정이든 떠나려는 사람을 붙잡을 필요는 없다. 하지만 당신과 끝까지 가려는 사람은 반드시 소중히 여겨야만 한다.", original: "", source: "『나는 내가 잘됐으면 좋겠다』", sourceLabel: "『나는 내가 잘됐으면 좋겠다』" },
  { id: "T02", person: "존 템플턴", ko: "영원한 강세장은 없습니다. 영원한 약세장도 없습니다.", original: "No bull market is permanent. No bear market is permanent.", source: "16가지 원칙 중 9번", sourceLabel: "16가지 원칙 중 9번", note: "16 Rules for Investment Success (1993)" },
  { id: "S092", person: "이소울", ko: "누가 너를 그렇게 아프게 했냐고 누군가 물었다. 나는 조용히 웃으며 이렇게 대답했다. '내가 품었던 기대감'이라고.", original: "", source: "인스타그램 이소울 게시글", sourceLabel: "인스타그램 이소울 게시글" },
  { id: "S093", person: "작자 미상", ko: "너무 생각하지 않는 편이 좋은 것 — 다른 사람의 기분, 카톡의 답장, 몸무게, 사는 의미, 이미 말해 버린 일, 사람들이 날 어떻게 생각하는가.", original: "", source: "펌글 · 캘리 happy_yuche", sourceLabel: "펌글 · 캘리 happy_yuche" },
  { id: "T03", person: "존 템플턴", ko: "모든 답을 안다는 투자자는 질문조차 다 이해하지 못한 것입니다.", original: "An investor who has all the answers doesn't even understand all the questions.", source: "16가지 원칙 중 14번", sourceLabel: "16가지 원칙 중 14번", note: "16 Rules for Investment Success (1993)" },
  { id: "S094", person: "작자 미상", ko: "인생은 XXX. 어제는 경험(Xperience), 오늘은 실험(Xperiment), 내일은 기대(Xpectation). 그러니 경험을 실험에 써서 기대를 이루세요.", original: "Life is XXX. Yesterday is Xperience, Today is Xperiment, Tomorrow is Xpectation. So use your Xperience in your Xperiment to achieve your Xpectation.", source: "선생님 사진첩 · 영문 카드", sourceLabel: "선생님 사진첩 · 영문 카드" },
  { id: "S095", person: "작자 미상", ko: "세상에서 가장 어려운 일은 꾸준히 하는 것입니다. 하지만 꾸준히 할 수 있게 되면 세상의 모든 것이 쉬워집니다.", original: "", source: "좋은 글 중 · 운산 최미숙 캘리", sourceLabel: "좋은 글 중 · 운산 최미숙 캘리" },
  { id: "T04", person: "존 템플턴", ko: "사실은 예전의 반복인데도 '이번엔 다르다'고 말하는 투자자는, 투자 역사에서 가장 값비싼 말을 한 것입니다.", original: "The investor who says, \"This time is different,\" when in fact it's virtually a repeat of an earlier situation, has uttered among the four most costly words in the annals of investing.", source: "16가지 원칙 중 11번", sourceLabel: "16가지 원칙 중 11번", note: "16 Rules for Investment Success (1993)" },
  { id: "S096", person: "이창섭", ko: "매일을 건강하게 살아가는 마음의 근육이 붙기를 기대해 본다.", original: "", source: "『적당한 사람』 · 캘리 happy_yuche", sourceLabel: "『적당한 사람』 · 캘리 happy_yuche" },
  { id: "S097", person: "드라마 『폭싹 속았수다』", ko: "엄마는 엄마대로 행복했어. 엄마 인생도 나름 쨍쨍했어. 그림 같은 순간들이 얼마나 많았다고. 그러니까 딸이 엄마 인생도 좀 인정해주라.", original: "", source: "드라마 대사 · 캘리 callilove", sourceLabel: "드라마 대사 · 캘리 callilove" },
  { id: "T05", person: "존 템플턴", ko: "분산하세요. 주식과 채권에서도, 다른 많은 일에서처럼, 여럿일 때 안전합니다.", original: "Diversify. In stocks and bonds, as in much else, there is safety in numbers.", source: "16가지 원칙 중 8번", sourceLabel: "16가지 원칙 중 8번", note: "16 Rules for Investment Success (1993)" },
  { id: "S098", person: "작자 미상", ko: "옆에서 봐야 소중함을 아는 사람은 기회를 줘도 소중함을 다시 잃기 마련이다.", original: "", source: "좋은 글 중 · 이공이오 삼월 · 고운은주글씨", sourceLabel: "좋은 글 중 · 이공이오 삼월 · 고운은주글씨" },
  { id: "S099", person: "하승완", ko: "영원한 건 세상에 없고 당연한 것도 없다. 그러니 마음을 표현할 수 있을 때 꼭 표현하고, 누군가 내게 건넨 진심을 절대 잊지 않기를 바란다.", original: "", source: "캘리 happy_yuche 게시글", sourceLabel: "캘리 happy_yuche 게시글" },
  { id: "S100", person: "무직타이거", ko: "스스로 작아지고 부족하게 느껴지면 이걸 꼭 기억해야 함. 그건 '사실'이 아니라 그냥 힘든 하루가 만든 '기분'일 뿐임. 다음 날이 되면 다시 괜찮아짐.", original: "", source: "캘리 happy_yuche 게시글", sourceLabel: "캘리 happy_yuche 게시글" },
  { id: "M01", person: "하워드 막스", ko: "세상에서 가장 위험한 것은 위험이 없다는 믿음이 널리 퍼지는 것입니다.", original: "The riskiest thing in the world is the widespread belief that there's no risk.", source: "메모 \"Risk Revisited\" 2014", sourceLabel: "메모 \"Risk Revisited\" 2014" },
  { id: "S101", person: "작자 미상", ko: "\"완벽\"을 내려놓으면 \"여유\"가 생기고, \"기대\"를 내려놓으면 \"고마움\"이 생기고, \"질투\"를 내려놓으면 \"나다움\"이 생기고, \"집착\"을 내려놓으면 \"선택지\"가 생긴다.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "S102", person: "은시런니", ko: "혹시 내가 말을 좀 세게 했거나 나 때문에 상처받는 일 많았다면 이제부터 그럴 일 없도록 내가 노력해.", original: "", source: "인스타그램 amy_3112 · 캘리 happy_yuche", sourceLabel: "인스타그램 amy_3112 · 캘리 happy_yuche" },
  { id: "M02", person: "하워드 막스", ko: "어디로 가는지는 알 수 없어도, 사이클에서 지금 어디쯤 있는지는 알아야 합니다.", original: "…while we can't know where we're going, we ought to know where we are (in cyclical terms).", source: "메모 \"It's All Good\" 2007", sourceLabel: "메모 \"It's All Good\" 2007" },
  { id: "S103", person: "작자 미상", ko: "어른이 되니 그냥 얼른 집에 도착해서 세상과 단절하고 잠만 자는 게 가장 큰 행복이란 걸 알아버림.", original: "", source: "펌글 · 캘리 happy_yuche", sourceLabel: "펌글 · 캘리 happy_yuche" },
  { id: "S104", person: "작자 미상", ko: "사실 \"별일 없어\"라는 말은 \"나의 힘듦이 너에게 짐이 될까 봐 말 못하겠어\"가 아닐까.", original: "", source: "인스타그램 damso_calli 캘리 게시글", sourceLabel: "인스타그램 damso_calli 캘리 게시글" },
  { id: "M03", person: "하워드 막스", ko: "대부분의 것은 결국 사이클을 그리고, 극단에서 평균 쪽으로 되돌아오는 경향이 있습니다.", original: "…most things eventually prove to be cyclical and tend to swing back from the extreme toward the mean.", source: "메모 \"Taking the Temperature\" 2023", sourceLabel: "메모 \"Taking the Temperature\" 2023" },
  { id: "S105", person: "박근호", ko: "행복은 틈틈이 챙겨야 해요. 날 잡고 챙기려고 하면 놓치거든요. 인생 짧습니다. 정말 너무 짧아요. 사는 동안 틈틈이 행복합시다.", original: "", source: "인스타그램 phugpark · 캘리 happy_yuche", sourceLabel: "인스타그램 phugpark · 캘리 happy_yuche" },
  { id: "S106", person: "작자 미상", ko: "넘어졌으면 다시 일어나면 된다. 추락했으면 다시 올라가면 된다. 무너졌으면 다시 일으키면 된다. 실패했으면 다시 시도하면 된다. 실수했으면 다시 만회하면 된다. 다시 할 기회는 언제나 존재한다. 당신에게는 늘 다시 할 힘이 있다.", original: "", source: "선생님 사진첩 · 그림 카드", sourceLabel: "선생님 사진첩 · 그림 카드" },
  { id: "S107", person: "백년", ko: "잘못된 습관이 있다면 고치면 되고, 잘 안될 땐 될 때까지 하면 되고, 길이 없으면 만들면 되고, 믿고 사는 세상에 살고자 한다면 속이지 않으면 되고, 미움 없이 살고자 한다면 사랑하고 용서하면 되고, 사랑받고 싶으면 부지런하고 성실하고 진실하면 되고. 이렇게 우리 인생은 하고자 하면 안 되는 게 없답니다.", original: "", source: "「하고자 한다면」 · 캘리 수록(천 족자)", sourceLabel: "「하고자 한다면」 · 캘리 수록(천 족자)" },
  { id: "C01", person: "찰리 멍거", ko: "아침에 일어났을 때보다 조금 더 현명해지려고 애쓰며 하루를 보내세요.", original: "Spend each day trying to be a little wiser than you were when you woke up.", source: "『가난한 찰리의 연감(Poor Charlie's Almanack)』", sourceLabel: "『가난한 찰리의 연감(Poor Charlie's Almanack)』" },
  { id: "S108", person: "하상욱", ko: "선택은 힘들다. 지금의 내가 감당해야 하니까. 후회는 두렵다. 나중의 내가 견뎌내야 하니까.", original: "", source: "『튜브, 힘낼지 말지는 내가 결정해』", sourceLabel: "『튜브, 힘낼지 말지는 내가 결정해』" },
  { id: "S109", person: "작자 미상", ko: "별생각이 다 들어도 걱정 마. 별일 안 일어나더라.", original: "", source: "『오늘도 잘 살았네』 · 캘리 happy_yuche", sourceLabel: "『오늘도 잘 살았네』 · 캘리 happy_yuche" },
  { id: "C02", person: "찰리 멍거", ko: "가장 똑똑하지도, 때로는 가장 부지런하지도 않은 사람들이 성공하는 걸 늘 봅니다. 그들은 배우는 기계입니다.", original: "I constantly see people rise in life who are not the smartest, sometimes not even the most diligent. But they are learning machines.", source: "USC 로스쿨 졸업식 연설 2007", sourceLabel: "USC 로스쿨 졸업식 연설 2007" },
  { id: "S110", person: "작자 미상", ko: "때로는 관계를 유지하기보다 거리를 유지하는 것이 더 현명하다.", original: "", source: "선생님 사진첩 · 감동명언 카드", sourceLabel: "선생님 사진첩 · 감동명언 카드" },
  { id: "S111", person: "작자 미상", ko: "강해져라, 그 누구도 널 망가뜨리지 못하게. 냉정해져라, 아니다 싶은 건 후회 없이 쳐 낼 수 있도록.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "J01", person: "존 보글", ko: "성과는 왔다가 가지만, 비용은 영원히 굴러갑니다.", original: "Performance comes and goes, but costs roll on forever.", source: "강연 \"In Investing, You Get What You Don't Pay For\" 2005", sourceLabel: "강연 \"In Investing, You Get What You Don't Pay For\" 2005" },
  { id: "S112", person: "작자 미상", ko: "존중받지 못한다면 거리를 두세요. 초대받지 않았다면 가지 마세요. 늦게 초대받았다면 거절하세요. 무시당하면 다가가지 마세요. 배신당했다면 용서하고 잊어버리세요. 잊었다면 그들도 잊으세요. 모욕당했다면 성공으로 답하세요. 항상 되고 싶었던 사람이 되기 시작하세요.", original: "", source: "인스타그램 릴스", sourceLabel: "인스타그램 릴스" },
  { id: "S113", person: "무직타이거", ko: "스트레스 받으면 왜 단 게 땡기는 줄 앎? Stressed(스트레스를 받은) 반대로 쓰면 Desserts(디저트)임.", original: "STRESSED ⇄ DESSERTS", source: "캘리 happy_yuche 게시글", sourceLabel: "캘리 happy_yuche 게시글" },
  { id: "J02", person: "존 보글", ko: "투자에서는 내지 않은 만큼 얻습니다.", original: "You get what you don't pay for.", source: "같은 강연 2005", sourceLabel: "같은 강연 2005" },
  { id: "S114", person: "작자 미상", ko: "용기를 내요, 조금 힘들면 어때요. 감당할 만큼만 시련을 준대요. 조금 부족하면 어때요, 다시 채우면 되지요. 남보다 못났다고 생각하지 말아요. 그들도 남모를 어려움이 있어요.", original: "", source: "『꿈이 있는 한 나이는 없다』 중에서 「괜찮아요」", sourceLabel: "『꿈이 있는 한 나이는 없다』 중에서 「괜찮아요」" },
  { id: "S115", person: "작자 미상", ko: "바깥세상은 우리 마음대로 할 수 없어도 우리 마음은 마음대로 할 수 있다. 이것을 알면 힘이 생길 것이다.", original: "", source: "마르쿠스 아우렐리우스 『명상록』의 말로 알려짐 · 원문 미확인 · 글반장", sourceLabel: "마르쿠스 아우렐리우스 『명상록』의 말로 알려짐 · 원문 미확인 · 글반장" },
  { id: "S116", person: "한창훈", ko: "가장 잘 사는 방법은 평범한 삶을 노련하게 사는 거라고 생각해요. 결국 인생은 평범한 거라는 것. 평범 안에서 노련하게, 인생에 이것 이상이 없는 것 같아요. 또 노련이라면 바람 방향을 읽을 줄 알고 어설프게 바다로 나가지 않는 것, 이런 거겠죠. 이 지루함까지 포함한 일상이 바로 평화인 겁니다.", original: "", source: "소설가 한창훈 · 인터뷰 카드", sourceLabel: "소설가 한창훈 · 인터뷰 카드" },
  { id: "J03", person: "존 보글", ko: "시간은 여러분의 친구이고, 충동은 여러분의 적입니다.", original: "Time Is Your Friend, Impulse Is Your Enemy", source: "『The Clash of the Cultures』 2012, 9장 원칙 2 제목", sourceLabel: "『The Clash of the Cultures』 2012, 9장 원칙 2 제목" },
  { id: "S117", person: "작자 미상", ko: "삶은 결국 생각하기 나름이야. 그 선택이 네 삶을 바꿀 거야.", original: "", source: "인스타그램 jason_j_cho · 캘리 happy_yuche", sourceLabel: "인스타그램 jason_j_cho · 캘리 happy_yuche" },
  { id: "S118", person: "빨강머리N", ko: "스스로 지옥에서 사는 방법이 뭔지 알아? 상대방의 말을 자꾸 해석하려 드는 거다.", original: "", source: "빨강머리N 그림 게시글", sourceLabel: "빨강머리N 그림 게시글" },
  { id: "J04", person: "존 보글", ko: "건초더미에서 바늘 찾기가 얼마나 어려운지 안다면, 그냥 건초더미를 사세요.", original: "When you understand how hard it is to find that needle, simply buy the haystack.", source: "『The Clash of the Cultures』 2012, 9장 원칙 5", sourceLabel: "『The Clash of the Cultures』 2012, 9장 원칙 5" },
  { id: "S119", person: "하승", ko: "지금 너의 힘듦은 행복의 거름이 되어 머지않아 미래에 웃으며 누구보다 예쁘게 피어날 거야.", original: "", source: "캘리 yuche 게시글", sourceLabel: "캘리 yuche 게시글" },
  { id: "S120", person: "작자 미상", ko: "돈이 인생의 전부는 아니다. 대부분이지… (인생 참 힘들다)", original: "", source: "선생님 사진첩 · 칠판 카드", sourceLabel: "선생님 사진첩 · 칠판 카드" },
  { id: "J05", person: "존 보글", ko: "투자의 비밀은 비밀이 없다는 것입니다.", original: "The secret to investing is that there is no secret.", source: "『The Clash of the Cultures』 2012, 9장 원칙 10", sourceLabel: "『The Clash of the Cultures』 2012, 9장 원칙 10" },
  { id: "S121", person: "작자 미상", ko: "사람과 사람 사이 중요한 건 달아오름이 아니라 식지 않는 것. 앞으로 나아가는 것이 아니라 처음으로 돌아가는 것.", original: "", source: "선생님 사진첩 · 책 페이지(저자 미확인)", sourceLabel: "선생님 사진첩 · 책 페이지(저자 미확인)" },
  { id: "S122", person: "김소월", ko: "먼 훗날 당신이 찾으시면 그때에 내 말이 \"잊었노라\". 당신이 속으로 나무라면 \"무척 그리다가 잊었노라\". 그래도 당신이 나무라면 \"믿기지 않아서 잊었노라\". 오늘도 어제도 아니 잊고 먼 훗날 그때에 \"잊었노라\".", original: "먼 後日 당신이 차즈시면 그때에 내 말이 「니젓노라」", source: "「먼 후일」 · 『진달래꽃』 1925(초출 『학생계』 1920)", sourceLabel: "「먼 후일」 · 『진달래꽃』 1925(초출 『학생계』 1920)" },
]

const EPOCH_UTC = Date.UTC(2026, 0, 1) // 2026-01-01 고정 기준일 — 이 값을 바꾸면 기존에 나간 날짜별 명언이 전부 바뀐다
const DAY_MS = 24 * 60 * 60 * 1000

/** todayKst 는 'YYYY-MM-DD' 형식의 KST 날짜 문자열. Date.now() 를 쓰지 않는 순수 함수 — 기준일부터 며칠째인지를 QUOTES.length 로 나눈 나머지로 순환한다(배열이 투자·삶을 섞어 둔 순서라 단순 순환으로 고르게 섞인다) */
export function quoteOfDay(todayKst: string): Quote {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(todayKst)
  if (!m) throw new Error(`quoteOfDay: 잘못된 날짜 형식 "${todayKst}" (YYYY-MM-DD 필요)`)
  const [, y, mo, d] = m
  const ts = Date.UTC(Number(y), Number(mo) - 1, Number(d))
  const days = Math.floor((ts - EPOCH_UTC) / DAY_MS)
  const idx = ((days % QUOTES.length) + QUOTES.length) % QUOTES.length
  return QUOTES[idx]
}
